// Auto-generated from resource.h by make_resource_rc.py
// Only the symbols actually referenced by resource.rc are kept.
// DO NOT EDIT MANUALLY.

#ifndef RESOURCE_R_H
#define RESOURCE_R_H

#define IDR_SAKURA_MENU                 102
#define IDD_DISP                        103
#define IDD_TALK                        104
#define IDD_SETUP                       105
#define IDD_NETWORKEXT                  106
#define IDD_NETWORK                     107
#define IDD_POP                         108
#define IDD_GHOSTPROFILE                109
#define IDR_SAKURA_CALENDAR_MENU        111
#define IDD_SCHEDULE                    112
#define IDD_MESSENGER                   113
#define IDD_MESSENGERUSER               114
#define IDD_MESSENGERSETTING            115
#define IDD_IPMESSENGERSETTING          117
#define IDD_EXTAPP                      118
#define IDD_LISTDIALOG                  120
#define IDR_LISTDIALOG_MENU             121
#define IDD_LOG                         123
#define IDD_PROPERTY                    124
#define IDR_KERO_MENU                   128
#define IDD_DEVELOPER                   131
#define IDD_DIRECTORYDROP               132
#define IDD_DEVPALETTE                  133
#define IDD_FOLDER                      134
#define IDD_FOLDEREDIT                  135
#define IDD_GHOST                       141
#define IDD_POPACCOUNT                  143
#define IDD_INTERNATIONAL               144
#define IDD_GHOSTEXT                    145
#define IDR_MESSENGER_MENU              148
#define IDR_LISTDIALOG_TOP_MENU         152
#define IDD_NOGHOST                     164
#define IDD_DICTATION                   165
#define IDD_DICTATIONSETTING            167
#define IDD_SAVESHARE                   173
#define IDD_GHOSTTERMS                  175
#define IDD_DEVSERIKODUMP               176
#define IDD_SEND_SHIORI_REQUEST         177
#define IDD_STREAMINGTOOL               178
#define IDD_VOICEAPI                    179
#define IDR_PICTURE_VIEWER_MENU         180
#define IDD_PV_RESIZE                   181
#define IDC_ACTIVATE_EXCEPTUPDATE       1002
#define IDC_ACTIVATE_OFF                1003
#define IDC_ACTIVATEWHENTALK            1004
#define IDC_ADDRESS                     1005
#define IDC_ADJUST_SERIKOWAIT           1006
#define IDC_AFTERBOOT                   1007
#define IDC_AI_INTERVAL                 1008
#define IDC_ALPHA_CALENDAR              1009
#define IDC_ALPHA_SAKURA                1010
#define IDC_ALPHA_SAKURAMSG             1011
#define IDC_APPLY_GHOST                 1014
#define IDC_ASSOCIATEFILE               1017
#define IDC_AUTO_UPDATE                 1018
#define IDC_AUTO_UPDATE_DURATION        1019
#define IDC_AUTOCHANGE                  1020
#define IDC_AUTOCHANGE_DURATION         1021
#define IDC_AUTOCHANGE_RANDOM           1022
#define IDC_AUTOCHANGE_SEQUENTIAL       1023
#define IDC_AUTOCLEAR                   1024
#define IDC_AUTOHEADLINE                1025
#define IDC_BALLOON_EDIT                1026
#define IDC_BALLOON_NUM                 1027
#define IDC_BALLOON_RELOAD              1028
#define IDC_BALLOON_SELECT              1029
#define IDC_BALLOONMOVE                 1030
#define IDC_BALLOON_SELECT_BOOT         1030
#define IDC_BALLOONTEST                 1031
#define IDC_BIFF_TYPE                   1032
#define IDC_BIRTHDAY                    1033
#define IDC_BROADCAST_ADD               1034
#define IDC_BROADCAST_DEL               1035
#define IDC_BROADCAST_EDIT              1036
#define IDC_BROADCAST_INIT              1037
#define IDC_BROADCAST_LIST              1038
#define IDC_CACHE_DURATION              1039
#define IDC_CACHE_ENABLE                1040
#define IDC_CACHE_LIST_ENABLE           1041
#define IDC_CACHE_NUM                   1042
#define IDC_CALLNAME                    1043
#define IDC_CHANGE_FMO_NAME             1044
#define IDC_CHANGESENDER                1045
#define IDC_CHECK_MAILHEADER            1048
#define IDC_CHECK_NOTIFYONLYNEW         1049
#define IDC_CHECK_NOTIFYWHENNEW         1050
#define IDC_CLEAR                       1051
#define IDC_CLICK_TIMEOUT               1052
#define IDC_CONNECTION_ASK              1055
#define IDC_CONNECTION_LIMIT            1056
#define IDC_CONNECTION_LIMIT_START      1057
#define IDC_CONNECTION_LIMIT_STOP       1058
#define IDC_COPY                        1059
#define IDC_CRAFTMAN                    1060
#define IDC_CRAFTMANURL                 1061
#define IDC_CREATE_SUBMENU              1063
#define IDC_CROSSFADER                  1064
#define IDC_DEACTIVATE                  1065
#define IDC_DEFAULT_BROWSER             1066
#define IDC_DEFAULT_EDITOR              1067
#define IDC_DEFAULT_FILER               1068
#define IDC_DEFAULT_GIT                 1069
#define IDC_DEFAULT_MAILER              1070
#define IDC_DEFAULT_MAILER_ARG          1071
#define IDC_DEFAULT_SVN                 1072
#define IDC_DEFINEDSURFACEONLY          1073
#define IDC_DESKTOP_OFFSET              1074
#define IDC_SCALING_BALLOON             1074
#define IDC_DEVFUNC_ENABLE              1075
#define IDC_DIR_BOTH                    1076
#define IDC_DIR_CREATENAR               1077
#define IDC_DIR_IGNORE                  1078
#define IDC_DIR_UPDATEDEF               1079
#define IDC_DIRECTIP                    1080
#define IDC_DISABLE_LOCK                1081
#define IDC_DISABLE_VANISH              1082
#define IDC_DLIST                       1083
#define IDC_DONTSETCURSOR               1084
#define IDC_DRAGDROP                    1085
#define IDC_DTOFFSET_SPIN               1086
#define IDC_DUMMYUPDATE                 1087
#define IDC_ENABLEPROXY                 1088
#define IDC_EXEC_OPEN                   1089
#define IDC_EXEC_RELOAD                 1090
#define IDC_EXECUTE                     1091
#define IDC_EXHANDLER                   1092
#define IDC_EXTENDMENUWIDTH             1093
#define IDC_FIRSTNAME                   1095
#define IDC_FLIP3D                      1096
#define IDC_FMO_NAME                    1097
#define IDC_FOLDER_NOAUTO               1098
#define IDC_FOLDER_NOAUTOUPDATE         1099
#define IDC_FOLDER_NOCHECK              1100
#define IDC_FOLDER_NORAND               1101
#define IDC_FOLDERADD                   1102
#define IDC_FOLDERDEL                   1103
#define IDC_FOLDERDN                    1104
#define IDC_FOLDEREDIT                  1105
#define IDC_FOLDERLIST                  1106
#define IDC_FOLDERMODIFY                1107
#define IDC_FOLDERUP                    1108
#define IDC_FONT_BALLOON_CHOICE         1109
#define IDC_FONT_BALLOON_DEFAULT        1110
#define IDC_FONT_BALLOON_SHOW           1111
#define IDC_FONT_MENU_CHOICE            1112
#define IDC_FONT_MENU_DEFAULT           1113
#define IDC_FONT_MENU_SHOW              1114
#define IDC_FORCEALIGNFREE              1115
#define IDC_FORCEALIGNLIMIT             1116
#define IDC_FORCEALIGNOFF               1117
#define IDC_GHOST_EDIT                  1119
#define IDC_GHOST_NUM                   1120
#define IDC_GHOST_RELOAD                1121
#define IDC_GHOST_SELECT                1122
#define IDC_GHOSTBOOT                   1123
#define IDC_GHOST_SELECT_BOOT           1123
#define IDC_GHOSTPROFILE                1124
#define IDC_GROUPNAME                   1125
#define IDC_HEADLINE_BROWSE             1126
#define IDC_HEADLINE_COUNT_MANUAL_UPDATE 1127
#define IDC_HEADLINE_EDIT               1128
#define IDC_HEADLINE_INTERVAL           1129
#define IDC_HEADLINE_INTERVAL_S         1130
#define IDC_HEADLINE_NONE               1131
#define IDC_HEADLINE_NUM                1132
#define IDC_HEADLINE_PLAY               1133
#define IDC_HEADLINE_RELOAD             1134
#define IDC_HEADLINE_SELECT             1135
#define IDC_HEADLINE_SOUNDPATH          1136
#define IDC_HELPFILE                    1137
#define IDC_HELPME                      1138
#define IDC_HIDE_SURFACEERR             1139
#define IDC_HIDEFULLSCREEN              1140
#define IDC_HISTORY_LIMIT               1141
#define IDC_HISTORY_LIMIT_SPIN          1142
#define IDC_HTTPADDRESS                 1143
#define IDC_PIN_VD                      1143
#define IDC_HTTPCHECK                   1144
#define IDC_IGNORE_UNINSTALL_HIDE       1145
#define IDC_IGNOREMOVE                  1146
#define IDC_INSTALL_README              1147
#define IDC_IPMESSENGER                 1148
#define IDC_IPMSGPORT                   1149
#define IDC_KASANARI                    1150
#define IDC_LEFTDC_SETTING              1152
#define IDC_LIST_INSTALLED_TO_FMO       1153
#define IDC_LOG                         1154
#define IDC_LOGLINE                     1155
#define IDC_MAKOTO_CHARSET              1156
#define IDC_MENU_HEIGHT                 1157
#define IDC_MENU_HEIGHT_SPIN            1158
#define IDC_MENU_LIMIT                  1159
#define IDC_MENU_LIMIT_SPIN             1160
#define IDC_MESSAGE                     1161
#define IDC_MESSAGELIST                 1162
#define IDC_MIKIRE                      1163
#define IDC_MOUSEOVER_NOTIMEOUT         1164
#define IDC_NAME                        1165
#define IDC_NAR_PATH                    1168
#define IDC_NARPATH_ASK                 1169
#define IDC_NARPATH_SAME                1170
#define IDC_NARPATH_USER                1171
#define IDC_NARPATH_USER_ASK            1172
#define IDC_NARPATH_USER_EDIT           1173
#define IDC_NO_SSTP_TRANSLATE_EVENT     1174
#define IDC_NO_WAIT_HEADLINE            1175
#define IDC_NOBLOCK_CHOICE              1176
#define IDC_NOMENUMODIFY                1177
#define IDC_NOTALKMINIMIZE              1178
#define IDC_NOTIFY_ERROR                1179
#define IDC_NOTRANSLATE                 1180
#define IDC_OKBUTTON                    1181
#define IDC_OPEN_ERRORLOG               1182
#define IDC_OPEN_SCRIPT                 1183
#define IDC_OPEN_SURFACETEST            1184
#define IDC_PIRO_CHARSET                1185
#define IDC_OPEN_TIMEMACHINE            1185
#define IDC_PLUGIN_EDIT                 1186
#define IDC_PLUGIN_NUM                  1187
#define IDC_PLUGIN_RELOAD               1188
#define IDC_PLUGIN_SELECT               1189
#define IDC_POP_ACCOUNT                 1190
#define IDC_POP_ADD                     1191
#define IDC_POP_ADDRESS                 1192
#define IDC_POP_AUTO                    1193
#define IDC_POP_BROWSE                  1194
#define IDC_POP_COPY                    1195
#define IDC_POP_DEL                     1196
#define IDC_POP_ID                      1197
#define IDC_POP_INTERVAL                1198
#define IDC_POP_INTERVAL_SPIN           1199
#define IDC_POP_LIST                    1200
#define IDC_POP_MODIFY                  1201
#define IDC_POP_NONE                    1202
#define IDC_POP_PASS                    1203
#define IDC_POP_PLAY                    1204
#define IDC_POP_MAILER_PATH             1204
#define IDC_POP_PORT                    1205
#define IDC_POP_PORT_DEFAULT            1206
#define IDC_POP_SOUNDPATH               1207
#define IDC_POP_SSL                     1208
#define IDC_POP_SSLVERIFY               1209
#define IDC_PORT                        1210
#define IDC_PROFILE_KIND                1212
#define IDC_PROTOCOL                    1213
#define IDC_PROXYADDRESS                1214
#define IDC_PROXYPASS                   1215
#define IDC_PROXYPORT                   1216
#define IDC_PROXYTYPE                   1217
#define IDC_PROXYUSER                   1218
#define IDC_RANDOMGHOSTBOOT             1219
#define IDC_REF_BROWSER                 1220
#define IDC_SELECTGHOSTBOOT             1220
#define IDC_REF_EDITOR                  1221
#define IDC_REF_FILER                   1222
#define IDC_REF_GIT                     1223
#define IDC_REF_MAILER                  1224
#define IDC_REF_SVN                     1225
#define IDC_REGISTER_HOTKEY             1226
#define IDC_RESET                       1227
#define IDC_RESET_GHOST                 1228
#define IDC_RESET_PROGRESS              1229
#define IDC_RESET_STATIC                1230
#define IDC_RIGHT_SETTING               1231
#define IDC_SAKURA_MUTEX                1232
#define IDC_SAVE                        1233
#define IDC_SCHEDULE_CAPTION            1239
#define IDC_SCHEDULE_CURRENTDATE        1240
#define IDC_SCHEDULE_DELETE             1241
#define IDC_SCHEDULE_ENDTIME            1242
#define IDC_SCHEDULE_LIST               1243
#define IDC_SCHEDULE_MONTH              1244
#define IDC_SCHEDULE_NEW                1245
#define IDC_SCHEDULE_NONE               1246
#define IDC_SCHEDULE_SCRIPT             1247
#define IDC_SCHEDULE_SUBTITLE           1248
#define IDC_SCHEDULE_TIME               1249
#define IDC_SCHEDULE_TIME_ENABLE        1250
#define IDC_SCHEDULE_TIMEEND_ENABLE     1251
#define IDC_SCHEDULE_TYPE               1252
#define IDC_SCHEDULE_DATE               1253
#define IDC_SCHEDULE_ENDDATE            1254
#define IDC_SCHEDULE_WEEK               1255
#define IDC_SCHEDULE_YEAR               1256
#define IDC_SCRIPT_CHARSET              1260
#define IDC_SELECTION_TIMEOUT           1261
#define IDC_SELFUPDATE_AUTO             1262
#define IDC_SEND                        1263
#define IDC_SET_DIRDROP                 1264
#define IDC_SEX_FEMALE                  1265
#define IDC_SEX_MALE                    1266
#define IDC_SEX_UNDEF                   1267
#define IDC_SHEETFRAME                  1268
#define IDC_SHEETS                      1269
#define IDC_SHIORI_CHARSET              1270
#define IDC_SHIORI_DEBUG_NOTIFY         1271
#define IDC_SHIORI_LOG                  1272
#define IDC_SHIORI_LOG_NOTIFY           1273
#define IDC_SHOW_HIDDEN_ELEMENTS        1274
#define IDC_SHOW_HITRECT                1275
#define IDC_SCALING_DITHER              1275
#define IDC_SHOW_THUMBNAIL              1276
#define IDC_SCALING_DITHER_BALLOON      1276
#define IDC_SHOWBALLOONONLINE           1277
#define IDC_SHOWICONALWAYS              1278
#define IDC_SNTP_AUTO                   1279
#define IDC_SNTP_DURATION               1280
#define IDC_SNTP_DURATION_SPIN          1281
#define IDC_SNTPADDRESS                 1282
#define IDC_SNTPCHECK                   1283
#define IDC_SOUND                       1285
#define IDC_SOUND_BROWSE                1286
#define IDC_SOUND_PATH                  1287
#define IDC_SPEEDUP                     1288
#define IDC_SPEEDUP_KEY                 1289
#define IDC_SPIN_AUTO_UPDATE_DURATION   1290
#define IDC_SPIN_AUTOCHANGE_DURATION    1291
#define IDC_SPIN_CACHE_DURATION         1292
#define IDC_SPIN_CACHE_NUM              1293
#define IDC_SPIN_TMPGHOST_INTERVAL      1294
#define IDC_SPIN_TMPGHOST_MAX           1295
#define IDC_SSL_VERIFY                  1296
#define IDC_SSTP_ADD                    1297
#define IDC_SSTP_DEL                    1298
#define IDC_SSTP_LIST                   1299
#define IDC_SSTP_LOG                    1300
#define IDC_SSTP_ONOFF                  1301
#define IDC_STATIC_LOGLINE              1302
#define IDC_STRICT_UPDATE               1306
#define IDC_STRICT_UPDATE_KEY           1307
#define IDC_TALK_BROWSE                 1311
#define IDC_TALK_NEWS                   1312
#define IDC_TALK_NONE                   1313
#define IDC_TALK_PLAY                   1314
#define IDC_TALK_SOUNDPATH              1315
#define IDC_TALK_SPEED                  1316
#define IDC_TALK_TIMEOUT                1317
#define IDC_TASKBAR                     1318
#define IDC_TEST                        1319
#define IDC_TITLEFRAME                  1320
#define IDC_TMPGHOST_INTERVAL           1321
#define IDC_TMPGHOST_MAX                1322
#define IDC_TOPMOST                     1323
#define IDC_TORTOISESVN                 1324
#define IDC_TYPE                        1325
#define IDC_UPDATE_BACKUPFILES          1326
#define IDC_UPDATE_CHECKOTHER           1327
#define IDC_UPDATE_DAU                  1328
#define IDC_UPDATE_IGNOREREADONLY       1329
#define IDC_UPDATE_TXT                  1331
#define IDC_UPDATECHECK_METHOD          1332
#define IDC_UPDATELIST                  1333
#define IDC_USE_DIALUP                  1334
#define IDC_USE_SYSTEM_SETTING          1335
#define IDC_USERDEL                     1336
#define IDC_USERNEW                     1337
#define IDC_USERPROP                    1338
#define IDC_USERTAB                     1339
#define IDC_DEV_STATIC                  1341
#define IDC_OPEN_SERIKO                 1349
#define IDC_SUPPRESS_EXIT               1354
#define IDC_SHOW_STATUS                 1355
#define IDC_TEMP_PATH                   1356
#define IDC_TEMP_PATH_REF               1357
#define IDC_TEMP_PATH_STATIC            1358
#define IDC_TEMP_PATH_DEFAULT           1359
#define IDC_NAR_PATH_STATIC             1360
#define IDC_NAR_PATH_DEFAULT            1361
#define IDC_NAR_PATH_REF                1362
#define IDC_CHECKBOX_SAMPLE             1363
#define IDC_ALT_MID_CLICK               1364
#define IDC_ALT_MID_CLICK_KEY           1365
#define IDC_ENABLE_TEST_UPDATE          1366
#define IDC_TAB_AUTO                    1370
#define IDC_TAB_ENABLE                  1371
#define IDC_TAB_DISABLE                 1372
#define IDC_DICTATION_TARGET            1373
#define IDC_DICTATION_COMMAND           1374
#define IDC_DICTATION_RESULT            1375
#define IDC_SENSOR_ENABLE               1376
#define IDC_DICTATION_LEVEL             1377
#define IDC_SENSOR_LOC                  1378
#define IDC_DICTATION_STATUS            1379
#define IDC_SENSOR_DISABLE              1380
#define IDC_DICTATION_RESULT_ST         1381
#define IDC_DICTATION_COMMAND_ST        1382
#define IDC_DICTATION_TARGET_ST         1383
#define IDC_DICTATION_ENGINE            1384
#define IDC_DICTATION_INPUT             1385
#define IDC_DICTATION_ENGINE_CONFIG     1386
#define IDC_DICTATION_INPUT_CONFIG      1387
#define IDC_DICTATION_PROFILE           1388
#define IDC_DICTATION_ENGINE_MIC        1390
#define IDC_DICTATION_ENGINE_TRAINING   1391
#define IDC_TTS_VOICE_0                 1392
#define IDC_TTS_VOICE_CONFIG_0          1393
#define IDC_TTS_OUTPUT                  1394
#define IDC_TTS_OUTPUT_CONFIG           1395
#define IDC_TTS_SPEED                   1396
#define IDC_TTS_LEVEL                   1397
#define IDC_SCALING_BUTTON              1403
#define IDC_CACHE_PROGRESS              1404
#define IDC_SAVESHARE_ENABLE            1406
#define IDC_SAVESHARE_PATH              1407
#define IDC_SAVESHARE_BROWSE            1408
#define IDC_SAVESHARE_DISP              1412
#define IDC_POP_MAILER_BROWSE           1415
#define IDC_POP_MAILER_ARG              1416
#define IDC_TTS_VOICE_1                 1417
#define IDC_TTS_VOICE_2                 1418
#define IDC_TTS_VOICE_CONFIG_1          1419
#define IDC_TTS_VOICE_CONFIG_2          1420
#define IDC_TTS_PITCH_0                 1421
#define IDC_TTS_PITCH_1                 1422
#define IDC_TTS_PITCH_2                 1423
#define IDC_BALLOON_SCALING_BUTTON      1424
#define IDC_HEADLINE_NO_TIMEOUT         1425
#define IDC_README_CHARSET              1426
#define IDC_DEFINE_CHARSET              1427
#define IDC_VIRUS_CHECK                 1429
#define IDC_DEFAULT_EDITOR_ARG          1430
#define IDC_FILE_CHARSET                1431
#define IDC_UPDATE_UTF8                 1432
#define IDC_GHOSTTERMS                  1433
#define IDC_PROFILE_CHARSET             1434
#define IDC_DEVSEREIKODUMP_LIST         1435
#define IDC_DEVSEREIKODUMP_ID           1436
#define IDC_DEVSEREIKODUMP_ID_SPIN      1437
#define IDC_CHECK_PARSE_RESPONSE        1438
#define IDC_SEND_EDIT                   1439
#define IDC_UPDATE_CACHE                1440
#define IDC_DEVSEREIKODUMP_PREFIX       1441
#define IDC_DEVSEREIKODUMP_GETCURRENT   1442
#define IDC_DEVSEREIKODUMP_DIR          1443
#define IDC_DEVSEREIKODUMP_DIRSELECT    1444
#define IDC_DEVSEREIKODUMP_FROMZERO     1445
#define IDC_BRING_OTHER_WINDOW_TO_FRONT 1446
#define IDC_DPI_AWARE                   1447
#define IDC_WINDOW_TOPLEVEL_CHAR        1448
#define IDC_WINDOW_TOPLEVEL_BALLOON     1449
#define IDC_SOUND_LEVEL_MONITOR_ENABLE  1450
#define IDC_SOUND_LEVEL_MONITOR_DEVICE  1451
#define IDC_SOUND_LEVEL_MONITOR_LEVEL   1452
#define IDC_SOUND_LEVEL_MONITOR_BAR     1453
#define IDC_TTS_SYNC                    1454
#define IDC_VOICE_ID                    1455
#define IDC_VOICE_HOST                  1456
#define IDC_VOICE_PORT                  1457
#define IDC_VOICE_APIKEY                1458
#define IDC_VOICE_VIEW                  1459
#define IDC_VOICE_TYPE                  1460
#define IDC_VOICE_STYLEID               1461
#define IDC_AUTOMOVE                    1462
#define IDC_CHECK_NOTIFY_MUSICPLAY      1463
#define IDC_DARK_AUTO                   1464
#define IDC_DARK_ENABLE                 1465
#define IDC_DARK_DISABLE                1466
#define IDC_SAVESHARE_SERVICE           1467
#define IDC_DEVSEREIKODUMP_DIROPEN      1468
#define IDC_PV_RESIZE_RADIO_PX          1470
#define IDC_PV_RESIZE_RADIO_PCT         1471
#define IDC_PV_RESIZE_EDIT_W            1472
#define IDC_PV_RESIZE_EDIT_H            1473
#define IDC_PV_RESIZE_KEEPRATIO         1474
#define IDC_PV_RESIZE_STATIC_CUR        1475
#define IDC_PV_RESIZE_STATIC_NEW        1476
#define SAKURA_CALENDAR_MENU_CENTER     5001
#define SAKURA_CALENDAR_MENU_CLOSE      5002
#define SAKURA_CALENDAR_MENU_DELETE     5003
#define SAKURA_CALENDAR_MENU_DELETEMONTH 5004
#define SAKURA_CALENDAR_MENU_DELETEYEAR 5005
#define SAKURA_CALENDAR_MENU_EDIT       5006
#define SAKURA_CALENDAR_MENU_NEXT       5007
#define SAKURA_CALENDAR_MENU_PREV       5008
#define SAKURA_CALENDAR_MENU_READEVENT  5009
#define SAKURA_CALENDAR_MENU_TODAYSSCHEDULE 5010
#define SAKURA_CALENDAR_MENU_TOPMOST    5011
#define LIST_CALLGHOST                  5012
#define LIST_COPY                       5013
#define LIST_CREATE_BOTH                5014
#define LIST_CREATE_NAR                 5015
#define LIST_CREATE_SHORTCUT            5016
#define LIST_DELETE                     5017
#define LIST_ENABLE                     5018
#define LIST_EXEC                       5019
#define LIST_FIND                       5020
#define LIST_FIND_NEXT                  5021
#define LIST_OPEN                       5022
#define LIST_PROP_AUTOCLOSE             5023
#define LIST_RELOAD                     5024
#define LIST_SELECTALL                  5025
#define LIST_SET_DEFAULT                5026
#define LIST_SET_PREFERRED              5027
#define LIST_TYPE_BALLOON               5028
#define LIST_TYPE_GHOST                 5029
#define LIST_TYPE_HEADLINE              5030
#define LIST_TYPE_PLUGIN                5031
#define LIST_TYPE_SHELL                 5032
#define LIST_UPDATE                     5033
#define LIST_UPDATE_CREATE              5034
#define LIST_UPDATE_RSS                 5035
#define LIST_URLJUMP                    5036
#define LIST_WEBJUMP                    5037
#define MESSENGER_MENU_LOGDEL           5038
#define SAKURA_MENU_ADDRESSBAR          5041
#define SAKURA_MENU_CALENDAR            5042
#define SAKURA_MENU_CHARSET             5043
#define SAKURA_MENU_CHECKUPDATE         5044
#define SAKURA_MENU_CLOSE               5045
#define SAKURA_MENU_CLOSEBALLOON        5046
#define SAKURA_MENU_COMPATIBLEMODE      5047
#define SAKURA_MENU_DEVELOPER           5048
#define SAKURA_MENU_EXIT                5049
#define SAKURA_MENU_EXPLORER            5050
#define SAKURA_MENU_GHOSTINFO           5051
#define SAKURA_MENU_GHOSTTIME           5052
#define SAKURA_MENU_HELP                5053
#define SAKURA_MENU_IM                  5054
#define SAKURA_MENU_KEEPGHOST           5055
#define SAKURA_MENU_LANG_RESET          5056
#define SAKURA_MENU_LEAVEPASSIVE        5057
#define SAKURA_MENU_MINIMIZE            5058
#define SAKURA_MENU_OPENDIR             5059
#define SAKURA_MENU_OPENFILE            5060
#define SAKURA_MENU_POP_ALLCHECK        5061
#define SAKURA_MENU_PROXY               5062
#define SAKURA_MENU_PURGEGHOSTCACHE     5063
#define SAKURA_MENU_RELOADGHOST         5064
#define SAKURA_MENU_RELOADINFO          5065
#define SAKURA_MENU_RESETBALLOON        5066
#define SAKURA_MENU_RESETPOS            5067
#define SAKURA_MENU_SCALING_FREE        5068
#define SAKURA_MENU_SCRIPTLOG           5070
#define SAKURA_MENU_SETUP               5071
#define SAKURA_MENU_SETUP_GHOST         5072
#define SAKURA_MENU_SNTP                5073
#define SAKURA_MENU_SYSTEMINFO          5075
#define SAKURA_MENU_TALKSHIORI          5076
#define SAKURA_MENU_UNINSTALL           5077
#define SAKURA_MENU_UPDATE              5078
#define SAKURA_MENU_UPDATEFMO           5079
#define SAKURA_MENU_VERSION             5080
#define LIST_OPEN_README                5081
#define SAKURA_MENU_AIGRAPH             5082
#define SAKURA_MENU_BIND_EXPLORER       5086
#define SAKURA_MENU_DICTATION           5087
#define SAKURA_MENU_TTS                 5088
#define LIST_CREATE_ZIPTXT              5089
#define LIST_UPDATE_CHECKONLY           5090
#define LIST_UPDATE_RSS_CHECKONLY       5091
#define LIST_CHECKONLY_CLEAR            5092
#define LIST_REGISTER_GHOSTS            5093
#define LIST_OPEN_SHELL                 5094
#define LIST_LOG_ENABLE                 5095
#define SAKURA_MENU_SCALING_BALLOON_FREE 5096
#define LIST_TYPE_LANGUAGE              5097
#define SAKURA_MENU_GHOSTTERMS          5098
#define LIST_CREATE_SHORTCUT_BOOTUP     5100
#define LIST_TYPE_CALENDAR_SKIN         5101
#define LIST_TYPE_SCHEDULE_SENSOR       5102
#define SAKURA_CALENDAR_MENU_DELETEFROMHERE 5103
#define SAKURA_CALENDAR_MENU_TODAY      5104
#define SAKURA_MENU_SCALING_CALENDAR_FREE 5105
#define PICTURE_MENU_SAVE               5107
#define PICTURE_MENU_COPY               5108
#define PICTURE_MENU_SAME               5109
#define PICTURE_MENU_ZOOMIN             5110
#define PICTURE_MENU_ZOOMOUT            5111
#define PICTURE_MENU_FIT                5112
#define PICTURE_MENU_PREV               5113
#define PICTURE_MENU_NEXT               5114
#define PICTURE_MENU_ROTATE_LEFT        5115
#define PICTURE_MENU_ROTATE_RIGHT       5116
#define PICTURE_MENU_FLIP_H             5117
#define PICTURE_MENU_BG_BLACK           5118
#define PICTURE_MENU_BG_WHITE           5119
#define PICTURE_MENU_BG_CHECKER         5120
#define PICTURE_MENU_OPEN               5122
#define PICTURE_MENU_RELOAD             5123
#define PICTURE_MENU_ZOOMCUSTOM         5124
#define SAKURA_MENU_PICTURE_VIEWER      5125
#define PICTURE_MENU_COLORKEY           5126
#define PICTURE_MENU_RESIZE             5127
#define PICTURE_MENU_TRIM               5128
#define PICTURE_MENU_PASTE              5129
#define SAKURA_MENU_BACKLOG_VIEWER      5131

#endif // RESOURCE_R_H
